### ISSUE TITLE
Erroneous mention of "with block"

### ISSUE THREAD

**Issue by keithellis74** [raspberrypilearning/push-button-stop-motion#12]
In the Push Button Stop Motion resource, the section titled 'Take a picture with python', 

https://github.com/raspberrypilearning/push-button-stop-motion/blob/master/worksheet.md#take-a-picture-with-python

In step 7, the line " inside the `with` block, so it becomes:"

The code shown does not have a `with` block.  reference to this should probably be removed.

**Comment by bennuttall** [comment]
Thanks
