### ISSUE TITLE
Worksheet images

### ISSUE THREAD

**Issue by LornaLynch** [raspberrypilearning/push-button-stop-motion#8]
Just a query: do we need images from Sam to replace the photos in the worksheet, or is it OK to leave these as they are?

**Comment by bennuttall** [comment]
I think we discussed this before. Can't remember why but I think we said no. Maybe a decent camera-attachment diagram would be helpful. We probably decided it would go in guides, and left it for that...

**Comment by LornaLynch** [comment]
Thanks, just as long as you guys are OK with it!
