### ISSUE TITLE
File naming for pictures is wrong, and not explained

### ISSUE THREAD

**Issue by navyscourge** [raspberrypilearning/push-button-stop-motion#9]
The names given to the pictures taken by the camera is inconsistent. A thread on the RPF Forums lead to this discovery: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=130747&sid=19af7ebe19235523bc29291b7330c144

Sections 2 to 5 use "imageN.jpg", where N is a number - these are single tests and not part of the 'video' that will be created, but the filename is not really explained. Perhaps add a note in 2.4 that this is a temporary name?

Section 6 starts taking pictures as part of a movie, using "frame%03d.jpg" in a Python program, which creates "frame001.jpg" and so on. Perhaps add an explanation of this format in this section?

Section 7 shows the 'avconv' command to create the movie. The filename is given as "animation/%03d.jpg". This should be "animation/frame%03d.jpg"

Perhaps consideration should also be given to creating a new folder/directory for this whole exercise, instead of using /home/pi, to make sure that users don't get mixed up with other files they may have created?

**Comment by bennuttall** [comment]
You're right - the `avconv` line is missing the word "frame". I've just fixed it.

I think the worksheet could do with some more explanation as you say. I'll leave this open until this has been addressed.

Thanks.
